export const thumbnails = [
  {
    title: 'Capacity Building',
    description: 'Empowering local communities through scalable solutions.',
    src: 'https://img.youtube.com/vi/2Hsv81h2l0I/hqdefault.jpg',
    alt: 'Thumbnail for Capacity Building',
    videoUrl: 'https://www.youtube.com/embed/2Hsv81h2l0I',
  },
  {
    title: 'Community Engagement',
    description: 'Strengthening local participation with actionable insights.',
    src: 'https://img.youtube.com/vi/ZhQDadpTfVI/hqdefault.jpg',
    alt: 'Thumbnail for Community Engagement',
    videoUrl: 'https://www.youtube.com/embed/ZhQDadpTfVI',
  },
  {
    title: 'Last Mile',
    description: 'Delivering impact where it matters the most.',
    src: 'https://img.youtube.com/vi/iZMcDp8dC5A/hqdefault.jpg',
    alt: 'Thumbnail for Last Mile',
    videoUrl: 'https://www.youtube.com/embed/iZMcDp8dC5A',
  },
  {
    title: 'Resilience Building',
    description: 'Enabling adaptive capacities for sustainable outcomes.',
    src: 'https://img.youtube.com/vi/sr5Yn066gZ8/hqdefault.jpg',
    alt: 'Thumbnail for Resilience Building',
    videoUrl: 'https://www.youtube.com/embed/sr5Yn066gZ8',
  },
  {
    title: 'Inclusive Partnerships',
    description: 'Catalyzing equitable development through stakeholder collaboration.',
    src: 'https://img.youtube.com/vi/2Hsv81h2l0I/hqdefault.jpg',
    alt: 'Thumbnail for Inclusive Partnerships',
    videoUrl: 'https://www.youtube.com/embed/2Hsv81h2l0I',
  },
  {
    title: 'Monitoring & Evaluation',
    description: 'Harnessing data to drive evidence-based decision-making.',
    src: 'https://img.youtube.com/vi/ZhQDadpTfVI/hqdefault.jpg',
    alt: 'Thumbnail for Monitoring & Evaluation',
    videoUrl: 'https://www.youtube.com/embed/ZhQDadpTfVI',
  },
  {
    title: 'Knowledge Sharing',
    description: 'Facilitating cross-sectoral learning for maximum reach.',
    src: 'https://img.youtube.com/vi/iZMcDp8dC5A/hqdefault.jpg',
    alt: 'Thumbnail for Knowledge Sharing',
    videoUrl: 'https://www.youtube.com/embed/iZMcDp8dC5A',
  },
  {
    title: 'Strategic Alignment',
    description: 'Driving systemic change through holistic frameworks.',
    src: 'https://img.youtube.com/vi/sr5Yn066gZ8/hqdefault.jpg',
    alt: 'Thumbnail for Strategic Alignment',
    videoUrl: 'https://www.youtube.com/embed/sr5Yn066gZ8',
  },
]
